controller_manager:
  ros__parameters:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50.0

    joint_trajectory_controller:
      type: controller_interface/ControllerBase
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
      type: "position_controllers/JointTrajectoryController"
      interface: "position"
      constraints:
        goal_time: 0.5
        stopped_velocity_tolerance: 0.1
